### ISSUE TITLE
Check for child/parent theme usage before attempting to add colors style/config overrides

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#130]
See PR: https://github.com/BoldGrid/starter/pull/2/commits/6520033384ddececbcda59b27795632a4fca0ee3#diff-78cd5aa3783a74555c9938a2a81d01c6R26

I haven't looked into this entirely, but the way it should work is that a child theme should check first it's own directory to see if the file exists, and if it does use that instead of the parent theme's stylesheet.  From what was reported, it looks like the parent theme's stylesheet is always getting loaded even when a child is setup and configured.  If that's the case, then we need to fix that.  It seems like there might be more going on as well, and things have changed a lot from v1 to v2 in terms of overriding now that we implemented the ability to have multiple sets of starter content.  The first issue I believe might just be checking all priorities in which these parts are loaded, and making sure that the example child theme sets the appropriate one to override config changes.

**Comment by jamesros161** [comment]
this is regarding using starter for making v1 themes, and is dead. closing.
