### ISSUE TITLE
Phantom Sidebar on homepage after changing from v1 to Crio

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#131]
**Describe the bug**
After changing from a v1 theme to Crio, I see a sidebar on the homepage when everything is set to No Sidebar.

**To Reproduce**
- Go thru inspirations process and install a site (I tested with Diced, Wedge, Cobalt, and Grid One with same results)
- Change theme to Crio
- Homepage has a sidebar, and *only* the homepage. Based on these settings, no sidebar should show:
-- Customizer > Design > Pages > Sidebar = none (this is the Global Setting)
-- Customizer > Design > Blog > Posts > Sidebar = none
-- Customizer > Design > Blog > Blog Page > Sidebar = none
-- Edit page > Page Template = Use Global Setting

If I go into the page and change the template from Use Global Setting to No Sidebar it fixes it

**Expected behavior**
I expect the page to use the global setting without me going into the page and resetting it.

**Additional context**
From a customer contact

**Comment by bwmarkle** [comment]
> I expect the page to use the global setting without me going into the page and resetting it.

@nicolepaschen  So the problem is that both V1 themes and Crio have templates named the same? So when the theme is switched, the template is still found and is not changed to the default?

**Comment by nicolepaschen** [comment]
No, they do not have templates named the same. When the theme is switched, the Customizer settings for Crio are not read properly. Everything in the Customizer is set to No Sidebar yet one still shows.

**Comment by bwmarkle** [comment]
Hi @jamesros161 can you take a look at this one when you get a chance?

**Comment by nicolepaschen** [comment]
we're never gonna solve this.
