### ISSUE TITLE
Crio - Site Pattern Backgrounds do not save to front end

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#135]
I published a site with an image background. Both the live preview and front end showed the image. Then I changed it to a pattern and published. The live preview showed the pattern but when I closed the Customizer I saw the image. When I opened the Customizer again the pattern was selected as active but the image background is in the live preview bc that's what's on the live site.

![pattern-background](https://user-images.githubusercontent.com/20601160/68226533-3cc72a80-ffc0-11e9-930c-8f332c41146b.PNG)

**Comment by nicolepaschen** [comment]
When I added a background image to test this, the Customzier panel flipped to Pattern & Color but the Background tab was still set to active. When I clicked Background nothing happened, I had to click on Pattern & Color tab first, then I could get back to the Background controls.

![background](https://user-images.githubusercontent.com/20601160/68323393-59806280-0093-11ea-8b04-b7bca3db16ec.gif)
![panel](https://user-images.githubusercontent.com/20601160/68323540-a6fccf80-0093-11ea-9c2c-6afb05aac7fe.gif)

**Comment by rramo012** [comment]
Can you create a new issue for this?

**Comment by nicolepaschen** [comment]
New issue created, original issue resolved
