### ISSUE TITLE
Confirm Email button moves around

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#143]
when using a v1 theme and WP 5.3 it asks me to confirm my admin email address. The button jumps to the right side of my screen when I try and click it for some reason, so I just have to skip it every time.

![jump-jump-around](https://user-images.githubusercontent.com/20601160/69167814-8ab15780-0ac3-11ea-8b1a-f3fb4691f7e9.gif)

Firefox.

**Comment by joe9663** [comment]
should be fixed when [this PR](https://github.com/BoldGrid/boldgrid-inspirations/pull/58) gets merged.

**Comment by rramo012** [comment]
Deployed

**Comment by bwmarkle** [comment]
Closing. Just resolved by release of latest Inspirations. Doesn't appear to be a bgtfw issue.
