### ISSUE TITLE
"Get Premium" Customizer buttons need updating

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-theme-framework#144]
Please see "Next Patch Release" references [here](https://docs.google.com/document/d/1J_g1m7MdwFhjJ51O_7lRTJy1YcxS5bN6fo9Cw1i1JCE/edit#heading=h.54r0ord8dhtd).

**Comment by jamesros161** [comment]
@bwmarkle I see that this was marked with the 2.1.13 milestone, was this resolved or does this still need to be updated?

**Comment by nicolepaschen** [comment]
old ticket, closing
