### ISSUE TITLE
Customizer JavaScript Conflict when Google Site Kit plugin is active

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#145]
**Describe the bug**
When the Google Site Kit plugin is installed, the Customize menu displays a repeating list of options due to a JavaScript error. 

**To Reproduce**
1. [Install WordPress with Crio and the Google Site Kit Plugin ](https://www.boldgrid.com/central/cloud-wordpress/try?theme=crio&plugins=google-site-kit)
2. Navigate to Appearance -> Customize
3. See error

**Expected behavior**
The Customize Menu should behave identically whether Google Site Kit is installed or not.

**Screenshots**
![Selection_278](https://user-images.githubusercontent.com/8019842/70472364-2fec9980-1a8c-11ea-8366-007ab2b8e4af.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Chrome

**Additional context**
The library src/assets/js/customizer/base-controls.js is loaded minified, regardless of the SCRIPT_DEBUG constant. The error from the minified JS is as follows:
```
base-controls.min.js?ver=5.3:1 Uncaught TypeError: u(...) is not a function
    at Object.<anonymous> (base-controls.min.js?ver=5.3:1)
    at r (base-controls.min.js?ver=5.3:1)
    at Object.<anonymous> (base-controls.min.js?ver=5.3:1)
    at r (base-controls.min.js?ver=5.3:1)
    at Object.<anonymous> (base-controls.min.js?ver=5.3:1)
    at r (base-controls.min.js?ver=5.3:1)
    at Object.<anonymous> (base-controls.min.js?ver=5.3:1)
    at r (base-controls.min.js?ver=5.3:1)
    at Object.2 (commons.js?ver=1.1.2:1)
    at r (base-controls.min.js?ver=5.3:1)
```

**Comment by rramo012** [comment]
This only affects the compiled version of the file. Could be a conflict between the 2 webpack builds.
Still needs more looking into.

**Comment by jessecowens** [comment]
@rramo012 This issue seems to be resolved now

**Comment by jamesros161** [comment]
issue resolved. closing
