### ISSUE TITLE
Crio + menu plugin = 2 hamburger menus

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#146]
I am using Crio Pro + Mega Max Menu.  When I enable Mega Max, desktop and tablet views show the mega menu as expected. However on mobile I see the mega menu AND a phantom hamburger menu icon from the framework. Clicking it doesn't do anything.

![crio-mega-mobile-menu](https://user-images.githubusercontent.com/20601160/72166603-8d2f7f80-3397-11ea-9b96-b06f0b19b6f5.PNG)

**Comment by timelsass** [comment]
for external plugins adding a hamburger or mobile menu styles - I would just disable the hamburger for the menu location :
![image](https://user-images.githubusercontent.com/11907254/72223149-fea73380-3539-11ea-8f4f-33a84f5956fa.png)

**Comment by nicolepaschen** [comment]
Yea, that works. I was thinking we should try and take care of that somehow for the user automatically but if they're advanced enough to use a different menu plugin, they can figure this out. Thanks!
