### ISSUE TITLE
background image controls not functioning

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#151]
using latest crio from https://wordpress.org/themes/crio/ and wp v5.3.2:

When going to customizer to change background > image , I uploaded a new background image.  I selected background image size as cover, and background effects as fixed.  The controls for scroll/fixed under Background Effects do not appear to work in the customizer, and once saving and publishing - the frontend does not have the correct changes as well.  

The repeat background image checkbox also does not appear to work.

No console errors appear, but am using minfied scripts.

Browser: chrome, ff, safari all behave the same.

Note: parallax effect does seem to work.

**Comment by jamesros161** [comment]
newer ticket duplicates this issue: https://github.com/BoldGrid/boldgrid-theme-framework/issues/193

Closing this ticket.
