### ISSUE TITLE
form styling from wp.org theme preview incomplete

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#152]
going to > https://wordpress.org/themes/crio/  > preview theme > elements (page) the form elements for file upload and clearing a form are not styled properly:

![image](https://user-images.githubusercontent.com/11907254/72216259-e9f07e80-34ec-11ea-880d-224bcc03eb84.png)

I think the buttons should match, or one aligned left and other right.  An input mask for the file upload button to match the theme's button styles would be a nice addition to the styles as well.

**Comment by jamesros161** [comment]
This issue appears to already be resolved

**Comment by rramo012** [comment]
I replicated
![image](https://user-images.githubusercontent.com/5629738/76877983-89622280-684a-11ea-9ade-fa0828458e0c.png)
