### ISSUE TITLE
link color not correct in widget areas

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#153]
When editing footer columns (possibly header columns as well), if the background color is selected as the first color in the palette, the link colors do not update to the correct colors when a users selects different colors from the palette for those controls.

This is using second position color with white links (correct):
![image](https://user-images.githubusercontent.com/11907254/72216439-10afb480-34ef-11ea-996c-ea4c43c9222a.png)

This is when i select the first position in the color palette, still with white links selected:
![image](https://user-images.githubusercontent.com/11907254/72216458-39d04500-34ef-11ea-91a0-b54a9c9e052f.png)

The link color reverts to using the same color as the background color selected (orange).

**Comment by nicolepaschen** [comment]
No longer an issue , closing ticket
