### ISSUE TITLE
Header Padding and Margin Controls Don't Work

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#159]
**Describe the bug**
The vertical Margin and Padding controls in the **Design -> Header -> Advanced** section do not affect the final height of the header area.

**To Reproduce**
1. [Install WordPress with Crio](https://www.boldgrid.com/central/cloud-wordpress/try?theme=crio)
2. Navigate to **Design -> Header -> Advanced -> Padding** or **Margin** and adjust the top or bottom values.
3. The preview will update (see below screenshots) but the published front-end does not change.

**Expected behavior**
The control should adjust the height of the header as desired. This is particularly important for displaying video backgrounds in their entirety without using Custom CSS.

**Screenshots**
Updating value in Customizer:
![20percent-padding](https://user-images.githubusercontent.com/8019842/74690281-b9f76380-519b-11ea-82ae-9d7622ba7b53.png)
Resulting front-end:
![20percent-padding-front-end](https://user-images.githubusercontent.com/8019842/74690310-d0052400-519b-11ea-82eb-7f561eafae6b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80.0.3987.106

**Additional context**
This issue has been reported several times in support forums and premium support tickets.

**Comment by nicolepaschen** [comment]
Resolved thank you
