### ISSUE TITLE
BoldGrid Attribution should not be toggleable without license

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-theme-framework#189]
Please see:
* https://github.com/BoldGrid/boldgrid-theme-framework/blob/1035fa858a2d80e11f8cb9cfd055461f1ebbed72/src/includes/customizer/class-boldgrid-framework-customizer-footer.php#L43-L51
* https://docs.google.com/spreadsheets/d/1VxnZ5ejNkpj2TIhJ1NxLsq9iJ7hZerQEA05J9VACBNo/edit#gid=0

**Comment by jessecowens** [comment]
Adding to Bug Scrub 2.8.1 Milestone. The current behavior where 1. The option is toggleable without a license and 2. The trash can "delete" icon does not function is frustrating for users.
