### ISSUE TITLE
Feature - Widget Controls for Header/Footer Layouts

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#226]
Working with Widgets in header / footer layouts is frustrating because there's no alignment controls like there are for other layout elements. For example, I cannot align this search box to be on the right side of the screen without custom css:
![search-header](https://user-images.githubusercontent.com/20601160/85469058-313e6900-b57b-11ea-9cc1-09f841ccfe99.PNG)

Controls:
![widget-controls](https://user-images.githubusercontent.com/20601160/85468842-f4727200-b57a-11ea-957d-9bf6ae086897.gif)

Request adding the directional arrows like the other things have.

**Comment by nicolepaschen** [comment]
There’s too much padding / margins on the widgets - needs controls so this can be a skinny row.

![image](https://user-images.githubusercontent.com/20601160/135141448-a23bafb2-cf5e-46e7-a64c-7f69d6508e33.png)

**Comment by jamesros161** [comment]
Add alignment control for widget areas.
Needs CSS changes for padding / margin on widgets.

**Comment by jamesros161** [comment]
Is this still necessary with the new Custom Footer templates?

**Comment by nicolepaschen** [comment]
users can use Custom Footer templates, closing ticket
