### ISSUE TITLE
Crio Links - Hover Color Brightness does not show in live preview

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#257]
Changing the Hover Color Brightness causes links to appear black on hover in the Customizer live preview - the front end is correct.

This control is found in several places including:
Design > Site Content > Links
Design > Blog > Blog Page > Links
Design > Blog > Posts > Links

![image](https://user-images.githubusercontent.com/20601160/88589332-f66e9b80-d026-11ea-93cd-c9a073a4ba6b.png)

![image](https://user-images.githubusercontent.com/20601160/88589409-169e5a80-d027-11ea-922c-15887ca72897.png)

**Comment by nicolepaschen** [comment]
![link-hover-effect](https://user-images.githubusercontent.com/20601160/122790526-6496ff00-d286-11eb-8a07-e15b07a71a30.gif)

When I change when the link is underlined, the hover brightness changes as well when it should not.

**Comment by nicolepaschen** [comment]
cannot replicate above anymore

**Comment by nicolepaschen** [comment]
WP 5.7 and RC3

My link color is a orangy-red color and I have the hover color brightness set to -25. In the live preview I see dark red when I hover on the link. When I publish and close the Customizer, I see a dark gray when I hover on the link.

When I have it set to 25, the live preview shows a correct lighter shade but the front end shows a light gray. 

![link-color](https://user-images.githubusercontent.com/20601160/123862638-977c6b00-d8f6-11eb-9b4e-eaf02efd8568.gif)

![front-end-light](https://user-images.githubusercontent.com/20601160/123863063-1a9dc100-d8f7-11eb-9229-a52e151a5d99.PNG)
![customizer-light](https://user-images.githubusercontent.com/20601160/123863065-1a9dc100-d8f7-11eb-8b1d-03018f900bdc.PNG)

**Comment by jamesros161** [comment]
Unable to replicate this issue. Following up with @nicolepaschen directly to troubleshoot
