### ISSUE TITLE
Clicking the Home icon in breadcrumb trail hangs for 5-7 seconds in customizer panels/sections

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#27]
When clicking on the various Home icons in the customizer, there is a noticeable delay before being moved to the main location after clicking on the icon:

![image](https://user-images.githubusercontent.com/11907254/49539988-f2fc2e80-f89c-11e8-94af-e3f46d633a0e.png)

Additional information:
BGTFW: v2.1.0
WP: 4.9.8
Tested in: Chrome/FF/Edge

**Comment by jamesros161** [comment]
Unable to replicate issue. This may have resolved in other updates / fixes
