### ISSUE TITLE
WP 5.5 + WooCommerce + v1 theme = fatal error cannot access any Woo pages

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#276]
When using WordPress 5.5 + current version of WooCommerce + current v1 theme I cannot visit the shop page, or any other WooCommerce pages. I can access the rest of the site.

![image](https://user-images.githubusercontent.com/20601160/90545543-ccf0ed80-e156-11ea-85fe-97ad881ddb21.png)

From a customer contact:
Fatal error: Uncaught Error: Call to undefined function wc_get_loop_prop() in /home/easter72/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php:376 Stack trace: #0 /home/easter72/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php(363): WC_Query->adjust_total_pages() #1 /home/easter72/public_html/wp-includes/class-wp-hook.php(289): WC_Query->handle_get_posts(Array) #2 /home/easter72/public_html/wp-includes/plugin.php(249): WP_Hook->apply_filters(Array, Array) #3 /home/easter72/public_html/wp-includes/class-wp-query.php(3190): apply_filters_ref_array('the_posts', Array) #4 /home/easter72/public_html/wp-includes/class-wp-query.php(3448): WP_Query->get_posts() #5 /home/easter72/public_html/wp-includes/class-wp-query.php(3559): WP_Query->query(Array) #6 /home/easter72/public_html/wp-includes/rewrite.php(612): WP_Query->__construct(Array) #7 /home/easter72/public_html/wp-content/themes/boldgrid-linx/inc/boldgrid-theme-framework/includes/class-boldgrid-framework-template-config.php(368): u in /home/easter72/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php on line 376

**Comment by jessecowens** [comment]
Issue does not occur with WooCommerce 4.3.3, 4.4.0 release was just a couple of hours before this bug was reported.

**Comment by jamesros161** [comment]
Issue is due to a bug in WooCommerce which is expected to be resolved in the WooCommerce 4.4.1 release. 
See https://github.com/woocommerce/woocommerce/issues/27394
