### ISSUE TITLE
header/footer widgets inheriting bootstrap body font

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#28]
It appears that header/footer sections are inheriting the font style declared by bootstrap.css.  These areas should inherit the customizer control for "Main Text", so that the user is able to change these.

![image](https://user-images.githubusercontent.com/11907254/49540206-8170b000-f89d-11e8-8653-2026370ef21d.png)

Additional Information:
BGTFW: 2.1.0
WP: 4.9.8
Tested in: Chrome/FF/Edge

**Comment by jamesros161** [comment]
Issue appears to have already been resolved
