### ISSUE TITLE
[Bug] Unable to set Featured Images for Blog Posts in V1 themes

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-theme-framework#290]
**Describe the bug**
Functionality to assign featured images to blog posts appears to be broken in V1 themes. A featured image can be selected, but saving/updating the post removes the image. Tested in Florentine, Callaway, and Cobalt. Crio did not have any issues.

**To Reproduce**
1. Install/activate any V1 theme
2. Create blog post and assign featured image
3. Save changes
4. Page refreshes with no featured image assigned to the post

**Comment by jessecowens** [comment]
This bug also affects other settings on the editor page, including "Display Post Title"
