### ISSUE TITLE
[Bug] Remove Selected Pattern button in V1 themes

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-theme-framework#318]
**Describe the bug**
An unintended background pattern appears when the Remove Selected Pattern button is used in the Customizer.

**To Reproduce**
1. Open the Customizer and got to Background > Pattern & Color
2. Select any pattern from the list and then click the Remove Selected Pattern button
3. Customizer preview should show a website background without a pattern
4. Publish/Update and then view the front end of the website.
5. Background color should display with the img/patterns/60-lines.png pattern

**Expected behavior**
Removed Selected Pattern should get rid of all patterns

**Screenshots**
![image](https://user-images.githubusercontent.com/17650704/99850827-1254fa80-2b4c-11eb-94e7-334ba338143b.png)

![image](https://user-images.githubusercontent.com/17650704/99850844-18e37200-2b4c-11eb-8391-7a852600961e.png)

**Comment by jessecowens** [comment]
[This issue was mentioned again in the BoldGrid User Forums](https://www.boldgrid.com/support/question/how-to-remove-the-background/#post-32089).

**Comment by jamesros161** [comment]
This was resolved in the BGTFW v1.7.10 release
