### ISSUE TITLE
"Older Posts" results in 404

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-theme-framework#325]
@jamesros161 please refer to private message.

**Comment by nicolepaschen** [comment]
This text should not appear on a category page not sure why it is.

**Comment by bwmarkle** [comment]
[JRos] Still troubleshooting. Will have time this week to review.

**Comment by bwmarkle** [comment]
[JRos] Problem from insp since its implementation. The blog page, instead of a "page" to display recent posts, the blog links to that category. This breaks some functionality. Period in category base - that's the problem. Ideal solution is to update Inspirations.
