### ISSUE TITLE
[Improvement] Add Menu Link Hover Color Control in Crio

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#328]
Design > Menus > (menu location) > Menu Items > Hover Style

Currently I cannot select a color to use for the menu link hover. All the hover effects do other things and the default hover effect lightens or darkens the current color.

Please add another color palette that only shows if 'No Hover Effects' is selected, and the menu links should appear this color on hover.

![let-me-pick-color](https://user-images.githubusercontent.com/20601160/103691080-9a0f9080-4f63-11eb-9d43-fd46315132fe.png)

**Comment by joe9663** [comment]
[+1 for this feature from the forums](https://www.boldgrid.com/support/question/?preview=true)

Adding a Custom Color option would be nice too.

**Comment by nicolepaschen** [comment]
The feature works as expected YAY. Can you please update the language in the dropdown from 'No Hover Effects' to 'Single Color' or 'Color Change' or something to indicate there still is a hover effect of some kind.

![menu-hover-color](https://user-images.githubusercontent.com/20601160/138139263-c943d1bf-ca02-4adc-b14e-a3b969597954.PNG)
