### ISSUE TITLE
[Feature] Add Option to Hide Excerpts on Blog Archive

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#345]
**Describe the solution you'd like**
In the Customize > Design > Blog > Blog Page Settings, add an option to completely hide the post excerpt.

**Describe alternatives you've considered**
There is an option to control the length of the excerpt, but setting it to 0 does not work as expected.

**Additional context**
This feature request is related to [user feedback in the comments on this article](https://www.boldgrid.com/support/boldgrid-crio-supertheme-product-guide/customizing-your-blog-page-with-boldgrid-crio/).

**Comment by nicolepaschen** [comment]
Setting the except length to 0 now works, closing ticket
