### ISSUE TITLE
text input doesn't line up with icon box next to it

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#36]
The input boxes are shorter than the orange box with the icon on the login and Product Search Widget. Firefox and Chrome.
![login-contrast](https://user-images.githubusercontent.com/20601160/50643669-bcb5db80-0f3c-11e9-8198-98b55c6ebd99.PNG)

**Comment by timelsass** [comment]
this template no longer exists in dev, so should be non-issue for the initial 2.1.1 Prime release
