### ISSUE TITLE
[Bug] WooCommerce Custom Ordering is Ignored

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#363]
**Describe the bug**
Using the Customizer option for WooCommerce > Product Catalog > Default Product Sorting > Default (Custom Order + Name), the order always reverts back to the published_on order.

**To Reproduce**
Steps to reproduce the behavior (detailed replication instructions in video below)
1. Install WordPress with Crio and WooCommerce
2. Import the demo products
   1. Navigate to Tools > Import
   2. Import WooCommerce Products > Show Advanced Options
   3. `wp-content/plugins/woocommerce/sample-data/sample_products.csv`
3. Navigate to Products > All Products > Sorting
4. Adjust order by dragging products to a new location in the list
5. Reload the page, and note that the products have reverted to their previous positions
https://user-images.githubusercontent.com/8019842/115454117-a69bba00-a1dd-11eb-98d4-43c2652bebac.mp4

**Expected behavior**
The template and dashboard menu should both respect the custom sort order set by the user.

**Additional context**
This bug was reported in the [BoldGrid User Forums](https://www.boldgrid.com/support/question/cant-sort-woocommerce-products-for-display-in-crio/).

**Comment by joe9663** [comment]
@jamesros161 +1 for this from the WordPress forums
