### ISSUE TITLE
WP 5.8 + Widgets (v1 and Crio)

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#421]
Using WP 5.8 Beta 2 and Crio 2.8 RC2

In Crio I cannot add standard widgets I get an error and cannot save the Customizer.

![image_(1)](https://user-images.githubusercontent.com/20601160/122601460-50ad8c00-d03f-11eb-8f64-fe390518d7cf.png)

**Comment by jamesros161** [comment]
This is likely a WP Core bug. Core Track ticket has been created: [https://core.trac.wordpress.org/ticket/53479](https://core.trac.wordpress.org/ticket/53479)
