### ISSUE TITLE
Bug Report: 'Go There Now' button in Customizer navigation problems

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-theme-framework#43]
**Describe the bug**
Clicking the Edit icon in the Customizer for elements contained in page content displays the 'Go There Now' button as expected.  However, the button does not navigate to the Page Editing interface as expected.

**To Reproduce**
1. Open the Customizer in any V1 theme.
2. Click on the Edit icon for page content elements.
3. See the popup containing the 'Go There Now' button directing the user to the page editing interface.
4. Click the button.
5. User is not redirected as expected.

**Expected behavior**
User should be taken to the page editing interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/45979457/53747593-9dbac380-3e71-11e9-8e3c-e67e82f7e4a4.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser: Firefox
 - Version: 64.0.1

**Additional context**
This behavior was replicated in Cloud WordPress and on a VPS.

Console also showed this error:

>Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://demo2.boldgrid.com/trial-63y0w8z9/wp-admin/customize.php?return=https://demo2.boldgrid.com/trial-63y0w8z9/wp-admin/' from frame with URL 'https://demo2.boldgrid.com/trial-63y0w8z9/?customize_changeset_uuid=a37b7120-a6ec-4066-89e5-1785c545c268&customize_theme=boldgrid-swifty&customize_messenger_channel=preview-0&customize_autosaved=on'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
>Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'https://demo2.boldgrid.com/trial-63y0w8z9/wp-admin/post.php?post=17&action=edit'.
>at HTMLDivElement.d.buttons.(anonymous function) (https://demo2.boldgrid.com/trial-63y0w8z9/wp-content/themes/boldgrid-swifty/inc/boldgrid-theme-framework/assets/js/customizer/edit.min.js?ver=1.2.2:1:1902)
>at HTMLButtonElement.d.click (https://demo2.boldgrid.com/trial-63y0w8z9/wp-includes/js/jquery/ui/dialog.min.js?ver=1.11.4:11:6517)
>at HTMLButtonElement.dispatch (https://demo2.boldgrid.com/trial-63y0w8z9/wp-includes/js/jquery/jquery.js?ver=1.12.4:3:12444)
>at HTMLButtonElement.r.handle (https://demo2.boldgrid.com/trial-63y0w8z9/wp-includes/js/jquery/jquery.js?ver=1.12.4:3:9173)
>d.buttons.(anonymous function) @ edit.min.js?ver=1.2.2:1
>d.click @ dialog.min.js?ver=1.11.4:11
>dispatch @ jquery.js?ver=1.12.4:3
>r.handle @ jquery.js?ver=1.12.4:3

**Comment by timelsass** [comment]
Does this happen in a regular install, or only on boldgrid.com hosted sites?

**Comment by boldgrid-support** [comment]
I was able to replicate it in a regular installation as well, bug does not appear to be limited to boldgrid.com installations.

**Comment by timelsass** [comment]
merged in v1 branch and released for BGTFW v1.6.0
