### ISSUE TITLE
Bug with edit buttons on blog page content

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#438]
I used the WP unit test data and the homepage is set to posts. When I click the buttons it always takes me to the Featured Image panel instead of the specific element I'm on.

Before I clicked the buttons by the post content, I clicked the body background button and I got overlapping panels in the Customizer (first part of gif)

![nothing-happens](https://user-images.githubusercontent.com/20601160/125676997-bd32ef05-c41a-4375-8b27-57e9c54a9713.gif)

**Comment by nicolepaschen** [comment]
The edit button by the post titles on the blog page should go to Design > Blog > Blog Page > Titles 

![image](https://user-images.githubusercontent.com/20601160/126507589-decf54b6-b09c-465e-8051-f51d1ebe963e.png)

**Comment by nicolepaschen** [comment]
Please have all these buttons go to Design > Blog > Blog Page > Post Meta

![Screenshot_1](https://user-images.githubusercontent.com/20601160/126508927-9703769a-31e6-4995-a9b1-73c1d50f80f8.jpg)

**Comment by nicolepaschen** [comment]
These two buttons aren't quite where I'd expect them - could they be in the upper corner?

![odd-placement](https://user-images.githubusercontent.com/20601160/126511780-36220959-30fc-4dd1-8257-842e7a0b358c.gif)

**Comment by jamesros161** [comment]
The exact positioning of the buttons is not going to always be where we want them, they get moved in order to prevent overlapping other edit buttons

**Comment by nicolepaschen** [comment]
The buttons by the sidebar widget links goes to the wrong panel. It currently goes to Body Links but they have their own control under Primary Sidebar > Links Color.

![widget-links](https://user-images.githubusercontent.com/20601160/127055810-1f06b9f5-4cb8-4e36-9fa8-2abf6cdd991d.gif)

**Comment by nicolepaschen** [comment]
The button on Post Page Titles should have a link to Page Title Styling as well. 

![page-title-styling](https://user-images.githubusercontent.com/20601160/127056374-85df75d6-3040-4975-9b5c-6a286c9dff6d.gif)

**Comment by nicolepaschen** [comment]
When using the Starter Content or Inspirations, there are buttons in the Post Meta that go to Body Links. Most times these links are controlled by Body Links but sometimes Inspirations use the config specifically set at Design > Blog > Blog Page > Post Meta

![blog-controls](https://user-images.githubusercontent.com/20601160/127056543-f775226c-3c34-4260-90d0-9dddd0273faa.gif)

When I use the WP Unit test data, these buttons do not appear:
![no-extra-things](https://user-images.githubusercontent.com/20601160/127056715-398b249a-829d-443c-9473-da23a740c504.jpg)

**Comment by nicolepaschen** [comment]
Post Navigation links at the bottom of each post currently have a Body Link button but they have their own control at Design > Blog > Posts > Links > Post Navigation Links

![Screenshot_2](https://user-images.githubusercontent.com/20601160/127198345-28c486a1-3c68-4659-9bc8-6c0246aad42a.jpg)

**Comment by nicolepaschen** [comment]
Pages have an option for background, container, sidebar but Posts are missing the background and container - sidebar is a separate button:

![missing-post-container](https://user-images.githubusercontent.com/20601160/127198494-83cf933f-11ef-4d55-9ca7-01ab5dee54e7.gif)

**Comment by nicolepaschen** [comment]
I cannot find a button for the container on Posts. There is a link to the Container/Background/Sidebar on pages. On posts, the sidebar has a separate button.

**Comment by nicolepaschen** [comment]
The buttons on the Blog Page go on top of the Sticky Header, except for the post with the image it appears:

![post-meta-sticky-header](https://user-images.githubusercontent.com/20601160/127950359-40977063-7314-4180-b668-3aaad606af43.gif)
