### ISSUE TITLE
link color not displayed in gutenberg editor

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#44]
**Describe the bug**
link colors not added in gutenberg

**To Reproduce**
1. Open a page with links in the gutenberg editor.

**Expected behavior**
The link color should be the same as the front end, but the styles aren't being applied.  Hover appears to be applied just not the the default color.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome/ff

**Additional context**
wp 5.1

**Comment by nicolepaschen** [comment]
very old ticket, closing.
