### ISSUE TITLE
Crio 2.9 RC1 - Requested Enhancements

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#441]
There are a few things I noticed:

- Should Attribution have a button by it?

- There seems to be an excessive amount of buttons for typography. Recommend showing less and no typography buttons in widgets so the user can get right to the widget

- Buttons by widgets are inconsistent - header/footer have them but sidebar doesn't

- The Branding Display button doesn’t seem helpful - it takes you to the default layout where the branding toggle doesn’t show.  Recommend removing this button or changing it so the default layout shows the checkboxes for the 3 branding elements.

- When clicking a typography button can the Heading or Main Text headings do the animated bounce so the user knows which one to change?

**Comment by nicolepaschen** [comment]
This seems like too many edit buttons in the sidebar, they all go to main text font:
![image](https://user-images.githubusercontent.com/20601160/126511950-75fdd5a6-1417-4ce0-b17a-83c177590ce5.png)

**Comment by jamesros161** [comment]
I don't think we should really have a button for the Attribution links, since we don't REALLY want people getting rid of them.
