### ISSUE TITLE
[Feature] Add Widget Areas to Sticky Header Layout

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#446]
**Is your feature request related to a problem? Please describe.**
Some users want their sticky header to precisely match their regular header layout to provide a consistent experience. 

**Describe the solution you'd like**
Allow Widget areas to be added to the Sticky Header Layout, or enable an option to use the existing regular header as a sticky header.

**Additional context**
This issue is related to feedback from the [BoldGrid Support Center](https://www.boldgrid.com/support/boldgrid-crio-supertheme-product-guide/customizing-the-header-design-in-boldgrid-crio/#comment-6804)

**Comment by smithikakart** [comment]
sticky header alignment feature also need like site header layout...
