### ISSUE TITLE
page/post titles not displayed since removal to premium

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#45]
**Describe the bug**
The page and post titles do not display since controls were removed into premium.

**To Reproduce**
1. Activate a theme using bgtfw, like prime.
2. view any page/post with thememods cleared.

**Expected behavior**
Page and post title should be displayed.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome/ff
 - Version: latest

**Additional context**
wp 5.1, wp 5.0

**Comment by rramo012** [comment]
Couple of issues here:

**Comment by timelsass** [comment]
Yeah I think for solution 3 this works, and is sorta expected as you said.  The control doesn't exist now, and isn't relevant to Prime's config.  The control and configuration values are added in the premium plugin, so those would override as they filter into the configs and would exit on the first loop's return when found.

When I think of ease of use from a user modifying configurations - I do think of the format a bit.  I think in the future we could change it to still be in the "controls" config since that's a convenient part of the config ( not having to set individual settings, and then set individual control defaults ), and throw a flag in which would ignore in the control creation loop part.  I don't think it's necessary to do that at this point though.

Since all controls/panels/sections are now in the config (well close to it), we can make bigger changes to the config format, when certain configs are loaded, and have old formats map to new ones for backwards compatibility if it's a breaking change/necessary.
