### ISSUE TITLE
Help button typography affected by body typography

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-theme-framework#471]
![image](https://user-images.githubusercontent.com/5925563/128343209-3076385d-dcaf-4fe5-bc13-f3c4e19d4379.png)

**Comment by jamesros161** [comment]
Which RC were you testing when you had this issue? This issue was raised in one of the other RCs, but the current RC ( RC3 ) this should be resolved, and I am unable to replicate it.

**Comment by bwmarkle** [comment]
I was using the last RC listed in project-sierra - 1.3.0-rc2
