### ISSUE TITLE
Are there controls / edit buttons for post meta?

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-theme-framework#472]
![image](https://user-images.githubusercontent.com/5925563/128343569-2af1af0e-9634-42bc-8e49-c4ca813be00a.png)

**Comment by nicolepaschen** [comment]
Yes but you need Pro enabled - was it enabled on this install?

**Comment by bwmarkle** [comment]
I simply clicked the "One Click Install" link for 1.3.0-rc2. Looks like the
crio premium zip was included, but I didn't log into central - so I
probably didn't have a premium key assigned.

**Comment by nicolepaschen** [comment]
I see the correct button when Pro is enabled. Without Pro you will not see the button bc you cannot do anything with Post Meta in free Crio. Closing ticket please reopen if needed.
