### ISSUE TITLE
[Bug] Adding another menu in Custom Layout doesn't assign menu to the location

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-theme-framework#477]
**Describe the bug**
Added a new menu with the Header Custom Layout controls and selected the menu with the dropdown. Published changes but the menu did not display in the expected location.

![image](https://user-images.githubusercontent.com/17650704/128561692-6dc99327-2d0a-4fc0-bb9e-c6c401fceb12.png)

Was able to get the menu to appear by assigning the Menu Location in Customize > Menus. Is that the expected behavior?

![image](https://user-images.githubusercontent.com/17650704/128561834-1346153a-ff33-4b0f-8abe-f316f2c2e714.png)

**Comment by joe9663** [comment]
Production version behaves this way too, so definitely not a blocker for this release. The dropdown in the layout controls is just establishing the menu location and never even attempts to assign anything to that location, correct?

**Comment by jamesros161** [comment]
This is the expected behavior. A menu is not automatically assigned to the location.

**Comment by joe9663** [comment]
That's what I get for naming my menu the same thing as the menu location, thanks for clearing that up!
