### ISSUE TITLE
[Bug] Footer Layout Delete Buttons are disabled in same row as Attribution

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#478]
**Describe the bug**
When Crio is active together with the [BoldGrid Connect](https://repo.boldgrid.com/boldgrid-connect.zip) IMH plugin, all delete buttons for the footer are disabled, not just the Attribution.

**To Reproduce**
1. Install an Inspiration with Crio
2. Install and activate the [BoldGrid Connect Plugin](https://repo.boldgrid.com/boldgrid-connect.zip)
3. Navigate to Footer Layout controls, and note that menus and widget areas do not have delete buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/8019842/128565082-a8e48921-b20c-4594-b6f2-c4971b19cde6.png)

**Comment by jessecowens** [comment]
@jamesros161 since this plugin is included in all IMH installs, I recommend prioritizing it with the upcoming release

**Comment by nicolepaschen** [comment]
This is happening to me on an install without the BG Connect Plugin - when I add a new row to the footer I do not see the trash icon. If I publish and close the Customizer and re-open, then I see the trash icon as expected.

**Comment by jessecowens** [comment]
@jamesros161 I was wrong about the correlation with BoldGrid Connect, it actually affects any elements that are in the same row as the attribution.

**Comment by nicolepaschen** [comment]
![image](https://user-images.githubusercontent.com/20601160/130635719-281f00d9-a64a-4987-bc7e-d084d0ab3d35.png)
