### ISSUE TITLE
replace icon-newpage.png with dashicons-external

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#48]
For resource documentation, I couldn't track down **icon-newpage.png** without asking a bunch of people where they got it from since it's used internally in other applications:

![image](https://raw.githubusercontent.com/BoldGrid/boldgrid-theme-framework/2.1.0/src/assets/img/icon-newpage.png)

After looking at the image itself, we can just replace this with [dashicons-external](https://developer.wordpress.org/resource/dashicons/#external) to avoid doing all that other stuff.

**Comment by rramo012** [comment]
![image](https://user-images.githubusercontent.com/5629738/54297181-b707f200-458c-11e9-87a3-a459a17e6cc1.png)

Tested
