### ISSUE TITLE
[Enhancement] Font control for buttons

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#506]
Sans-serif fonts are the generally the standard for buttons because sans-serif fonts are very readable. Right now the buttons inherit the Main Text font. It would be helpful if they had their own input in the Fonts panel in the Customizer. 

![image](https://user-images.githubusercontent.com/20601160/135137980-e86c788f-01d6-4b9d-b60f-6f0b328cc13d.png)

**Comment by jamesros161** [comment]
Button fonts should be set in the Customizer > Font panel
