### ISSUE TITLE
[Feature Request] Hamburger Menus on Tablet / Desktop

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#512]
I would like to design websites that use a hamburger menu on tablet and/or desktop as well as mobile. Can a control please be added to menus for this functionality?

**Comment by joe9663** [comment]
@nicolepaschen user had a similar request about 6 months ago. i was able to get the hamburger menu displayed on desktops with this CSS

```
@media only screen and (min-width: 768px) {
    .standard-menu-enabled .bgtfw-sticky-header input:not(:checked):not(.hidden)~.sm-clean {
        display: none;
    }
    .standard-menu-enabled .bgtfw-sticky-header label[id$=-menu-btn] {
        position: relative;
        top: unset;
    }
}
```
that might help you make your design until we add a solution within the framework.

**Comment by jamesros161** [comment]
Add a control to the 'Hamburger Menu' panel to let user select which device sizes use hamburger menus

**Comment by nicolepaschen** [comment]
Beta 1 - I installed the Coherent Inspiration:
![image](https://user-images.githubusercontent.com/20601160/148804772-8c7735c5-7118-47a1-a395-af20ec40179c.png)

On tablet there is a horizontal scrollbar. This doesn't happen on stable. It's coming from the social menu in the footer.
![footer-social-scroll](https://user-images.githubusercontent.com/20601160/148805138-d5dea733-8fc7-4ca0-a631-4141f1a4708f.jpg)

**Comment by nicolepaschen** [comment]
Please move this new control above the Hamburger Style selection otherwise it could get missed
![image](https://user-images.githubusercontent.com/20601160/148839122-3cf7d8f8-b3ed-46fc-b462-191c9b31ae9a.png)

**Comment by nicolepaschen** [comment]
Beta 1 - I cannot get menus in Custom Header Templates to use a hamburger menu on any screensize now.

**Comment by nicolepaschen** [comment]
I cannot align the hamburger menu when working with the Custom Header Layouts in the Customizer.
![menu-location](https://user-images.githubusercontent.com/20601160/150020768-482293c7-52ae-4121-a237-e32918e766ab.PNG)

**Comment by nicolepaschen** [comment]
The alignment in Custom Page Headers doesn't work either:

![image](https://user-images.githubusercontent.com/20601160/150021174-a86b8dca-4015-49e0-a99d-ac8beb67c410.png)

**Comment by nicolepaschen** [comment]
Still an issue in RC2
![hamburger-menu-custom-header](https://user-images.githubusercontent.com/20601160/151049636-011abd58-7eea-4f27-ab30-79e7790e0e6c.gif)

**Comment by nicolepaschen** [comment]
Hamburger menu doesn't not work as expected with the side header (Monument) Inspiration when enabled on desktop
