### ISSUE TITLE
[Bug] Inconsistent hover effect on links

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#513]
In the Customizer I have the Site Content > Links set to underline on hover without changing color brightness:
![image](https://user-images.githubusercontent.com/20601160/136017523-455fea7e-6a37-42da-99d8-fae5007a8551.png)

The link in the content respects this setting. However the links in the main part of the footer change to a lighter shade on hover, while the attribution changes to darker. 
![inconsistent-hover-effects](https://user-images.githubusercontent.com/20601160/136015539-24950556-b5b7-46ab-afff-6af3b3708cde.gif)

The hover effects across the site should be consistent please.

**Comment by jamesros161** [comment]
Inconsistency is mainly with Attribute links
