### ISSUE TITLE
Crio Starter Content not using neutral color for site background

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#529]
The 6th palette position is the site's 'neutral color' and should be the main background color for the site. Right now the background is responding to position 4 with the Starter Content and other non-Inspiration installs:

![neutral-color](https://user-images.githubusercontent.com/20601160/139856852-a04d725a-f8f1-4dbf-a6b4-d695f07cb905.gif)

**Comment by nicolepaschen** [comment]
Check the config for Background > Pattern & Color it should be set to the 6th position there.

**Comment by jamesros161** [comment]
resolved by commit [93468c5](https://github.com/BoldGrid/prime/commit/93468c58975f92880f178e9a9e9ca4176cc0cca3)
