### ISSUE TITLE
Footer social media menu doesn't respond to menu controls

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#533]
Starter Content - Pro is not active
If I go right to the social media menu I can style the colors. If I change the footer link colors, the social media menu then uses that setting and the menu design no longer works.

![footer-social-menu-link-color](https://user-images.githubusercontent.com/20601160/140120531-ed2697cc-4c33-487b-8201-77bb71eda70c.gif)

**Comment by jamesros161** [comment]
This is present in stable. Moving out of 2.9.5 project

**Comment by nicolepaschen** [comment]
Cannot replicate, closing
