### ISSUE TITLE
Update notice about Header Background Video now that it can show on all pages

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#535]
We updated the header background video functionality to work on all pages, not just the homepage. The Customizer notice still says it's homepage only.

![yes-yes-it-does](https://user-images.githubusercontent.com/20601160/140373971-a889efea-4c3d-4d80-9d5e-057c19828b59.PNG)

**Comment by jamesros161** [comment]
he notification displayed is done by WP Core, whenever you're on a page not included in the `video-active-callback`  method.
That warning only appears if the video background is set to 'Home Only'

If it's set to 'All Pages' that notification goes away
