### ISSUE TITLE
Custom Template 'Page Title' does not use calculated Heading Font Size values.

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/boldgrid-theme-framework#553]
The `.bgc-heading.bgc-page-title` class is getting it's font-size from the `bgtfw_heading_font_size` control directly, rather than getting the calculated value. This causes them to have the h5 font size, rather than the font size calculated for an h1. 

This may be due to the fact that the `.bgc-heading.bgc-page-title` doesn't contain an 'h' class. Consider adding `.h5` or `.h1` to the class depending on what heading size is chosen.

**Comment by nicolepaschen** [comment]
When I change the Heading Typography, it also changes the Site Title in a Custom Page Header. When I hover over the Site Title the text goes smaller. If I close the Customizer the Site Title goes back to the normal size:

![heading-controls-site-title](https://user-images.githubusercontent.com/20601160/150002407-cc3a1337-b66c-45a7-8c1c-4484015517d2.gif)

Site Title might need it's own responsive controls here:
![image](https://user-images.githubusercontent.com/20601160/150002800-fcc6d39a-132d-4da3-9c50-1cfbd2db8eef.png)

**Comment by nicolepaschen** [comment]
Also see https://github.com/BoldGrid/boldgrid-theme-framework/issues/557

**Comment by nicolepaschen** [comment]
I have the Site Title in a footer layout - when I hover on it another font appears:
![site-title-glitch](https://user-images.githubusercontent.com/20601160/150190039-52af0641-6a0f-42a5-9891-4bec13bcaf6d.gif)
