### ISSUE TITLE
Make button text responsive

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/boldgrid-theme-framework#556]
Buttons should not respond to the main text responsive values - since they are getting a new control in the Customizer responsive controls should be there.

Also we need to consider how the padding should change on the button as font size does.
![image](https://user-images.githubusercontent.com/49331357/146062256-5835f2a1-10c8-461c-bab8-83932330f46c.png)
![image](https://user-images.githubusercontent.com/49331357/146062275-376f433e-60d6-4be2-bf50-200cf4a70263.png)

**Comment by nicolepaschen** [comment]
in Beta 1 the responsive font control box is in the heading section not buttons:

![image (1)](https://user-images.githubusercontent.com/20601160/148794518-7d0b79fa-4d24-4a9d-bb62-bfa2c3edda10.png)
![image](https://user-images.githubusercontent.com/20601160/148794519-e5fa3447-db57-43a0-af84-1e250c6cf163.png)
