### ISSUE TITLE
Font weights do not change in the live preview

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/boldgrid-theme-framework#558]

**Comment by jamesros161** [comment]
![image](https://user-images.githubusercontent.com/49331357/146062736-0992ab0b-49a4-4900-a367-796a68fd8700.png)

**Comment by nicolepaschen** [comment]
Still an issue in RC2. If I select italic the font weight changes but without italic it won't:

![font-weight](https://user-images.githubusercontent.com/20601160/146478172-61b52e76-5c9d-4fb7-a66b-911be3d111e8.gif)

**Comment by nicolepaschen** [comment]
RC3 - when I change the heading font weight the main text font weight changes with it in the live preview:
![font-variants](https://user-images.githubusercontent.com/20601160/146609679-738aeb92-1959-409a-a083-675dcfe6f613.gif)
