### ISSUE TITLE
Remove max-full-width container margins from mobile / tablet screens

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/boldgrid-theme-framework#560]

**Comment by nicolepaschen** [comment]
That looks like it's due to the 'margin-left: auto; margin-right: auto' added to max-width containers, to keep them centered.
3:42 PM
I need to remove that rule for mobile.

**Comment by nicolepaschen** [comment]
I have a row with 4 columns and only an image in each column. When I change to the new container type the content jumps towards the center when it should not:

![container-jump](https://user-images.githubusercontent.com/20601160/146481715-91f217b7-629b-414f-a5ed-bc220cbc0464.gif)

**Comment by nicolepaschen** [comment]
Pages set to Full Width Container
Sidebar on right
Full width sections push past the edge of the screen

can't see left border:
![image](https://user-images.githubusercontent.com/20601160/146951565-e0ba704c-e43a-4154-bfe4-22d55087233d.png)

Content pushing off:
![image](https://user-images.githubusercontent.com/20601160/146951597-f6d9b28f-59b1-4a04-8e50-1e3065cce251.png)

**Comment by nicolepaschen** [comment]
![image](https://user-images.githubusercontent.com/20601160/146955633-39d41095-3c2f-4c25-8c02-0d5944281623.png)

left sidebar content overlaps a tiny bit into the sidebar

**Comment by jamesros161** [comment]
Closing this issue, because this feature is being removed from this patch, and will be implemented in a different method next patch
