### ISSUE TITLE
Hamburger Menu does not display on tablet sided screens.  

### ISSUE THREAD

**Issue by SitesByYogi** [BoldGrid/boldgrid-theme-framework#576]
**Is your feature request related to a problem? Please describe.**
- Tablets can't make use of hover effects, so it doesn't make any sense to use the desktop menu design at the tablet screen size.

This functionality was correct up until the 2.1.3 update

**Describe the solution you'd like**
- Tablet (medium) screen sizes should include at least the option to display hamburger Menu
**Describe alternatives you've considered**

- Maybe a third party plugin that offers this functionality.

**Comment by nicolepaschen** [comment]
Hamburger menus can now be used on any screensize, closing ticket.
