### ISSUE TITLE
(Sprout) Crio doesn't load sa_templates properly

### ISSUE THREAD

**Issue by elanasparkle** [BoldGrid/boldgrid-theme-framework#620]
When you install Crio from scratch the /wp-content/themes/crio/sa_templates/ folder is created with Theme overrides that force the user to use a custom theme. This in turn overrides any customization they could do in Sprout Invoices -> General Settings -> Theme options

**To Reproduce**
1. Go to Install Crio
2. Click on Set up an invoice and view the invoice
3. Folder created in the file system. (Which Shouldn't be there). 
4. Invoice will look like: 

![image](https://user-images.githubusercontent.com/5271694/153924701-defb354a-035b-4a7d-80e0-f6f233e5b1a1.png)
![image](https://user-images.githubusercontent.com/5271694/153924679-a3b0d112-9a23-4db3-9240-6c8fce2f281c.png)

**Expected behavior**
The folder should not be created and the theme should display on any of the four themes in Sprout Invoices.

**Comment by elanasparkle** [comment]
The best option is to get it to work without that folder being created if it can't be worked around to where it will display properly then uploading the custom template from here would make the best options. 

https://github.com/elanasparkle/Slate_Template

However, doing this forces the user to use a custom template and they CANT change it. Without going into the code of the pages to change anything.

**Comment by jamesros161** [comment]
Acceptance testing complete:
https://github.com/BoldGrid/boldgrid-theme-framework/pull/746#pullrequestreview-1130104234
