### ISSUE TITLE
fresh_site install doesn't apply link color to footer links

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#65]
It looks like an install with `get_option( 'fresh_site' ) === 1` doesn't apply footer link colors to the attribution areas.  I believe the classes just need to be added to the filters for that block, but I'm not 100% sure on that off the top of my head.

**Comment by timelsass** [comment]
Another note: it appears this only impacts the initial view in the customizer, but not the frontend after publishing.

**Comment by nicolepaschen** [comment]
no longer an issue
