### ISSUE TITLE
Beta 2 - Max Full Width starting px values

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#653]
Does it make sense all 3 screen sizes start at 1920? To see space on the side of a full width container I had to change small desktop to 950 and tablet to 725.

**Comment by jamesros161** [comment]
I set the defaults to the following:
large: 1920
desktop: 1200
tablet: 992

This sets the defaults for desktop and tablet to the maximum amount of their breakpoints, so that there will only be extra space if the user chooses
