### ISSUE TITLE
RC1 - Featured Images do not respect MFW

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#669]
I have my blog posts set to MFW at 1920. I have Design > Blog > Posts > Featured Images set to Below Header / Medium / None. The featured image does not stay within the 1920 boundary.

**Comment by nicolepaschen** [comment]
Left aligned really messes things up

**Comment by jamesros161** [comment]
Closing this because it's an edge case usage, that has no clear resolution
