### ISSUE TITLE
add responsive oembeds

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#68]
In exploration of other themes, and ideas for a better experience for users -- it seems like responsive ombeds are a nice feature to have.  One implementation I ran across was https://github.com/Automattic/jetpack/blob/7.1.1/modules/theme-tools/responsive-videos.php/#L102 - which might be something worth implementing within the theme framework.

**Comment by nicolepaschen** [comment]
https://github.com/BoldGrid/post-and-page-builder/issues/184
