### ISSUE TITLE
[Feature] Rich Submenus using PPB post types

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#714]
Create custom submenus with the PPB similar to those on OpenMetal.io:
Code example https://github.com/BoldGrid/openmetal-features/blob/b586d5a81a855261a9911d45cd8147da999fd60f/public/class-openmetal-features-public.php#L138

**Comment by jessecowens** [comment]
https://github.com/BoldGrid/openmetal-features/blob/b0d844d6edb71eb51559ca706559fe8b2d917f7d/admin/class-openmetal-features-admin.php#L130

**Comment by jamesros161** [comment]
Resolved in 2.18.0
