### ISSUE TITLE
[Bug] Featured Image background for Posts does not display

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-theme-framework#717]
**Describe the bug**
So this one is really weird. When installing an Inspiration, if you choose to add a blog then you cannot get a featured image to display as the background on a Post's page. Featured image background works as expected if you don't choose to add a blog during the Inspirations process.

**To Reproduce**
1. Start a new Inspiration and choose to add a blog.
2. Set a featured image for one of the blog posts.
3. Open up the Customizer and navigate to Design > Blog > Posts > Featured Image.
4. Make sure Display is set to Show and Position is Header Background.
5. View the Post you set a featured image for.
6. The background behind the Post title and meta information should remain a solid color instead of using an image.

_Note: Changing the Position setting from Header Background to Below Header correctly displays the featured image._

_Note: This behavior does not happen on version 2.6.0_

**Comment by jamesros161** [comment]
resolved in commit https://github.com/BoldGrid/prime/commit/75e3343c9e31762115a301de0d93d45fb4a4ddf0
