### ISSUE TITLE
Changing Color Palette changes page content

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#750]
1. Use DH Dentistry design
2. Change the color palette in the Customizer
3. View the cosmetic-dentistry page - you'll see the section background in the 3rd block no longer hits the side and a closing </div> was stripped from the first section
![disappearing-divs](https://user-images.githubusercontent.com/20601160/194382629-25c2f4cc-cde3-40be-9f63-5caa854d1041.gif)

**Comment by jamesros161** [comment]
[This code is likely what is responsible for this](https://github.com/BoldGrid/boldgrid-theme-framework/blob/fe7dd119ba2e1ad9c8d49a5a3f38b6321b460eb8/src/includes/customizer/class-boldgrid-framework-customizer-colors.php#L356)
