### ISSUE TITLE
PHP 8.1 installing recommended plugins

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#776]
When activating Crio on an installation with PHP 8.1 and 8.0 (unless that only happened bc I was on 8.1 originally and then downgraded) there are errors when activating recommended plugins when using the checkboxes.

1. Use installation with PHP8.1 and BoldGrid Connect Plugin (IMH Central installs)
2. Activate Crio by searching the wp.org repo
3. Click Begin Installing Plugins
4. Use the checkboxes to install one or both recommended plugins
5. See error in dashboard

Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /home/wordpress/doc_root/wp-admin/includes/class-bulk-upgrader-skin.php:156 Stack trace: #0 /home/wordpress/doc_root/wp-admin/includes/class-bulk-upgrader-skin.php(156): sprintf('%1$s installed ...', 'BoldGrid Easy S...') #1 /home/wordpress/doc_root/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/tgm/class-tgm-plugin-activation.php(3544): Bulk_Upgrader_Skin->after('BoldGrid Easy S...') #2 /home/wordpress/doc_root/wp-admin/includes/class-wp-upgrader.php(825): TGMPA_Bulk_Installer_Skin->after() #3 /home/wordpress/doc_root/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/tgm/class-tgm-plugin-activation.php(3164): WP_Upgrader->run(Array) #4 /home/wordpress/doc_root/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/tgm/class-tgm-plugin-activation.php(3277): TGMPA_Bulk_Installer->run(Array) #5 /home/wordpress/doc_root/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/tgm/class-tgm-plugin-activation.php(2884): TGMPA_Bulk_Installer->bulk_install(Array) #6 /home/wordpress/doc_root/wp-content/themes/crio/inc/boldgrid-theme-framework/includes/tgm/class-tgm-plugin-activation.php(650): TGMPA_List_Table->process_bulk_actions() #7 /home/wordpress/doc_root/wp-includes/class-wp-hook.php(308): TGM_Plugin_Activation->install_plugins_page('') #8 /home/wordpress/doc_root/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #9 /home/wordpress/doc_root/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #10 /home/wordpress/doc_root/wp-admin/admin.php(259): do_action('appearance_page...') #11 /home/wordpress/doc_root/wp-admin/themes.php(10): require_once('/home/wordpress...') #12 {main} thrown in /home/wordpress/doc_root/wp-admin/includes/class-bulk-upgrader-skin.php on line 156

![error](https://user-images.githubusercontent.com/20601160/207688836-85e5b4fd-52bf-4ec4-a19b-d1dfd4650d9f.gif)

This also leads to a front end error:

Warning: Trying to access array offset on value of type null in/home/wordpress/doc_root/wp-content/plugins/boldgrid-connect-feature-rest-api/includes/class-boldgrid-connect-service.phpon line58
Warning: Trying to access array offset on value of type null in/home/wordpress/doc_root/wp-content/plugins/boldgrid-connect-feature-rest-api/includes/class-boldgrid-connect-service.phpon line58

![image (1)](https://user-images.githubusercontent.com/20601160/207689854-57cf6f5e-6f7b-4134-ba44-c22eb6f35f76.png)

This process also breaks the wp-admin link from IMH-Central 
![image (2)](https://user-images.githubusercontent.com/20601160/207690227-b30dd383-abc0-4568-a99d-496bd7611654.png)

**Comment by nicolepaschen** [comment]
Without the BG Connect plugin I get the error in the dashboard, but not the front end error on PHP8
![image](https://user-images.githubusercontent.com/20601160/207694603-9eb41a2e-1f3b-4af7-a824-70dde5e4e20c.png)

**Comment by jamesros161** [comment]
The following errors are not related at all to Crio
```Warning: Trying to access array offset on value of type null in/home/wordpress/doc_root/wp-content/plugins/boldgrid-connect-feature-rest-api/includes/class-boldgrid-connect-service.phpon line58
Warning: Trying to access array offset on value of type null in/home/wordpress/doc_root/wp-content/plugins/boldgrid-connect-feature-rest-api/includes/class-boldgrid-connect-service.phpon line58```

These are actually being caused by a completely unrelated issue with the boldgrid connect plugin
