### ISSUE TITLE
Crio menu background isn't full width when set to full width

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#83]
**Describe the bug**
The menu background color does not touch the sides of screen when container is set to Full Width with Crio.

**To Reproduce**
1. Activate Crio
2. Make a header layout with a menu in a Full Width container
3. Add a background color to the menu
4. The color does not touch the sides of the screen.

**Expected behavior**
I expect the color to hit the sides of the screen - be truly full width.
If I remove the left/right padding on the column it looks as expected.

**Screenshots**
![header-not-full-wdith](https://user-images.githubusercontent.com/20601160/57153746-1a501c80-6da5-11e9-8822-1a9261e3e723.gif)
![menu-background-gap](https://user-images.githubusercontent.com/20601160/57153752-1de3a380-6da5-11e9-948c-269b17a670e3.PNG)

**Comment by timelsass** [comment]
The structure of the header follows the same structure as the BoldGrid Editor plugin's structure for content.  The best way to see how that is structured is to inspect the area, but essentially the structure is something like:

`
<boldgrid-section>
    <container>
        <row>
            <col>
                <menu>
            </col>
        </row>
    </container>
</boldgrid-section>
`

The controls in the customizer for header area are a temporary solution, and ideally we will use the editor's interface for dragging and resizing columns/rows/sections/etc, or perhaps with the introduction of Gutenberg into the customizer we will use that.  Either way though, the menu background color that is displayed above, appears like it is working and the background color is set.  There aren't currently controls for setting colors/padding/height/margin/etc for sections, rows, or columns independently.
