### ISSUE TITLE
Bug: Parallax for Site Background

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-theme-framework#87]
**Describe the bug**
When the parallax option is set for the Site Background in the Customizer it disables the parallax from working on any boldgrid-section configured in the page content.  Using Scroll or Fixed on Site Background does not produce this bug.

**To Reproduce**
1. Go to the Site Background settings in the Customizer
2. Configure an image background with the parallax option
3. Edit a page and set a parallax background for a section in the visual editor
4. View the page from the front end
5. The background for the section will scroll with the content and will not have the parallax behavior.

**Expected behavior**
Parallax backgrounds in the page content should function regardless of the Site Background settings.

**Desktop:**
 - OS: Fedora 28
 - Browser: Firefox, Chromium

**Comment by timelsass** [comment]
https://github.com/BoldGrid/boldgrid-theme-framework/commit/269cc4b5163fbdfee3a0449d94a28d4d862ef3d3 should resolve this issue from BGTFW in v2 themes.  This wouldn't touch v1 themes unfortunately.  I believe that this same issue may still occur if a user uses [Post and Page Builder by BoldGrid](https://wordpress.org/plugins/post-and-page-builder/), and sets more than one `.boldgrid-section` with a parallax background using that plugin.
