### ISSUE TITLE
Customizer Fonts Panel - font doesn't match other panels

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-theme-framework#94]
**Describe the bug**
Customizer > Fonts 
The text for Main Text and Headings on this panel appear bolder than text in other panels.

**To Reproduce**
1. Install Crio 2.2
2. Open the Customizer
3. Click on Fonts
4. See bold text

**Expected behavior**
I expect the text to look the same as other panels.

**Screenshots**
![firefox-font-panel](https://user-images.githubusercontent.com/20601160/57787727-f0331e80-7703-11e9-92a6-ef10f1e66465.PNG)
![chrome-font-panel](https://user-images.githubusercontent.com/20601160/57787730-f1fce200-7703-11e9-986b-dfb56ae696a8.PNG)

**Desktop (please complete the following information):**
Firefox and Chrome

**Additional context**
This might be a duplicate but I can't find the original ticket anymore

**Comment by timelsass** [comment]
Once #84 is resolved, these won't exist anymore, so there won't be any changes to address this in the mean time.  Current progress towards this is happening on the [typography](https://github.com/BoldGrid/boldgrid-theme-framework/tree/typography) branch for reference.
